### ISSUE TITLE
Create an Implementation of 2048 using coffeescript

### ISSUE THREAD

**Issue by DillonDepeel** [DillonDepeel/2048-in-every-programming-language#3]
use the coffeescript programming language to create a basic 2048 program.

**Comment by Sekhmet0208** [comment]
Hello , Can i work on this issue ?

**Comment by DillonDepeel** [comment]
yes please do! that would be excellent!

**Comment by Sekhmet0208** [comment]
Hello i finished an implementation , could you tell me how to push ?

**Comment by Sekhmet0208** [comment]
I'm having an error i think i need your permission ?
